---
- name: Ensure old versions of Docker are not installed.
  become: true
  ansible.builtin.shell: "for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done"

#- name: Ensure dependencies are installed.
#  become: true
#  ansible.builtin.apt:
#   pakage:
#   - apt-transport-https
#   - ca-certificates
#  state: present

- name: Create a directory /etc/apt/keyrings if it does not exist
  become: true
  ansible.builtin.file:
   path: /etc/apt/keyrings
   state: directory
   mode: '0755'

- name: Add Docker apt-key
  become: true
  ansible.builtin.get_url:
   url: https://download.docker.com/linux/ubuntu/gpg
   dest: /etc/apt/keyrings/docker-apt-keyring.asc
   mode: '0644'
   force: true

- name: Add Docker's APT repository
  become: true
  ansible.builtin.apt_repository:
   repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
   state: present
   update_cache: yes

- name: install docker
  become: true
  ansible.builtin.apt:
   package:
    - ca-certificates
    - apt-transport-https
    - docker-ce
    - docker-ce-cli
    - containerd.io
   update_cache: true