---
- name: Group module demo
  hosts: all
  become: true
  vars:
    mygroup: "example"
  tasks:
    - name: Delete group
      ansible.builtin.group:
        name: "{{ mygroup }}"
        state: absent
